# Docker Compose override for development
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  app:
    build:
      target: development
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app:/app/VectorDBRAG:/app/agent_system:/app/shared_agents
    volumes:
      # Mount source code for live reloading
      - ./VectorDBRAG:/app/VectorDBRAG
      - ./agent_system:/app/agent_system
      - ./shared_agents:/app/shared_agents
      - ./start_unified_interface.py:/app/start_unified_interface.py
      # Mount development tools
      - ./logs:/app/logs
      - ~/.gitconfig:/home/app/.gitconfig:ro
      - ~/.ssh:/home/app/.ssh:ro
    ports:
      - "5001:5001"
      - "8888:8888"  # Jupyter notebook port
    command: ["/app/start-dev.sh"]
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

  redis:
    ports:
      - "6379:6379"  # Expose Redis port for development tools
