version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_CLIENT=pg
      - DB_NAME=disc_assessment
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - API_PREFIX=/api
      - LOG_LEVEL=info
    depends_on:
      - db
    restart: always
    command: npm run start:prod

  # Database service (PostgreSQL)
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=disc_assessment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

volumes:
  postgres_data: