version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_CLIENT=sqlite3
      - DB_NAME=disc_assessment_dev
      - JWT_SECRET=development_secret_key
      - API_PREFIX=/api
      - LOG_LEVEL=debug
    depends_on:
      - db
    command: npm run dev

  # Database service (PostgreSQL for production, commented out for development which uses SQLite)
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=disc_assessment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Comment the following line to use PostgreSQL instead of SQLite in development
    profiles: ["production"]

volumes:
  postgres_data: