development:
  api:
    rate_limit: 1000/hour
    timeout: 60
  debug: true
  testing: true
production:
  api:
    max_concurrent_requests: 10
    rate_limit: 100/hour
    timeout: 30
  debug: false
  image_generation:
    cache_duration: 3600
    default_resolution: 1024x1024
    max_images_per_request: 5
    quality: hd
  monitoring:
    health_check_interval: 30
    logging_level: INFO
    metrics_enabled: true
    performance_tracking: true
  scraping:
    delay_between_requests: 1
    retry_attempts: 3
    timeout: 30
    user_agent_rotation: true
  security:
    api_key_required: true
    cors_origins:
    - http://localhost:3000
    - https://yourdomain.com
    max_request_size: 10MB
  testing: false
